using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System;

namespace Content.Client.Respawn;

[GenerateTypedNameReferences]
public sealed partial class RespawnConfirmWindow : DefaultWindow
{
    public event Action? OnConfirm;
    public event Action? OnCancel;

    public RespawnConfirmWindow()
    {
        RobustXamlLoader.Load(this);

        SetLoadingText();

        ConfirmButton.OnPressed += _ => OnConfirm?.Invoke();
        CancelButton.OnPressed += _ => OnCancel?.Invoke();
    }

    private void SetLoadingText()
    {
        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(
            "Ви точно хочете респавнитися?\n\n" +
            "[color=#f58231]Після респавну у вас зніметься 20% коштів Вашого персонажа.[/color]\n" +
            "Штраф складе: [color=red][bold]***[/bold][/color] кр."
        );
        MessageLabel.SetMessage(msg);
    }

    public void SetPenalty(int penalty)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(
            "Ви точно хочете респавнитися?\n\n" +
            "[color=#f58231]Після респавну у вас зніметься 20% коштів Вашого персонажа.[/color]\n" +
            $"Штраф складе: [color=red][bold]{penalty}[/bold][/color] кр."
        );
        
        MessageLabel.SetMessage(msg);
    }
}
